Update README.adoc
OpenLiberty/guide-microprofile-graphql pull request #45
Opened 2021-09-28 14:04 UTC by priyyanshi

Addressing #44

2021-09-28 16:33 UTC, dmuelle requested changes
looks good, just two minor edit suggestions

2021-09-28 16:33 UTC, dmuelle commented on README.adoc
> +Compared to REST, GraphQL services require less data fetching resulting in lower applications loading times and lower data transfer costs,
suggested edit:

GraphQL services require less data fetching than REST services, which results in lower application load times and lower data transfer costs. GraphQL also enables clients to better customize requests to the server.

2021-09-28 16:33 UTC, dmuelle commented on README.adoc
> +You will define object types `java`, `systemMetrics`, and `systemInfo` by creating and applying annotations to the `JavaInfo`, `SystemMetrics`, and `SystemInfo` classes respectively.
You will define  `java`, `systemMetrics`, and `systemInfo` object types..

2021-09-28 19:50 UTC, dmuelle approved these changes
LGTM, thanks

2021-09-30 07:48 UTC, ramkumar-k-9286 approved these changes

2021-09-30 07:49 UTC, ramkumar-k-9286 commented
LGTM

Regards,
Ramkumar

2021-09-30 16:43 UTC, merged